name: sk_flutter_downloader
description: A plugin for creating and managing download tasks. Supports iOS and Android.
version: 1.6.1-sk.3
homepage: https://github.com/fluttercommunity/flutter_downloader
maintainer: Hung Duy Ha (@hnvn)
publish_to: https://pub.intern.sk

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.3'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
